### ISSUE TITLE
Problem to plot black quantiles

### ISSUE THREAD

**Issue by VeroBordeaux** [GRousselet/rogme#10]
Hello
Thanks a lot for this package. I have now a problem which is new. When I do the example in your page the black lines for quantiles don't appear. I have this error message :
 `> p <- plot_scat2(df,
+                 xlabel = "",
+                 ylabel = "Scores (a.u.)",
+                 alpha = .3,
+                 shape = 21,
+                 colour = "grey10",
+                 fill = "grey90") #> scatterplots
> p <- plot_hd_links(p, sf[[1]],
+                    q_size = 1,
+                    md_size = 1.5,
+                    add_rect = TRUE,
+                    rect_alpha = 0.1,
+                    rect_col = "grey50",
+                    add_lab = TRUE,
+                    text_size = 5) #> superimposed deciles + rectangle
Warning messages:
1: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
2: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
3: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
4: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
5: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
6: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
7: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
8: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
9: Ignoring unknown parameters: fun.y, fun.ymin, fun.ymax
> p <- p + coord_flip() #> flip axes
> p
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
No summary function supplied, defaulting to `mean_se()`
`
What can I do for this ?

Thanks a lot

**Comment by GRousselet** [comment]
Hi, I think the problem is due to a recent ggplot2 update. I've changed the `plot_hd_links` function, which solves the problem in the README example. Let me know if it works for you.

**Comment by VeroBordeaux** [comment]
> Hi, I think the problem is due to a recent ggplot2 update. I've changed the `plot_hd_links` function, which solves the problem in the README example. Let me know if it works for you.

Hello, yes it works. Thanks a lot.
