### ISSUE TITLE
plot_kde_rug_dec1/2 functions throw errors (+fix)

### ISSUE THREAD

**Issue by QuantPsychiatry** [GRousselet/rogme#2]
Even when using data frames made from the `mkt2` function, I both `plot_kde_rug_dec` functions throw errors. Interrogating the code a bit, I found the problems in the first two lines, which are identical for both functions. 

The following lines:

  `cdat <- plyr::ddply(data, "gr", summarise, deciles=q1469(data))`
  `hd05 <- plyr::ddply(data, "gr", summarise, hd=hd(data,0.5))`

should be changed to

  `cdat <- plyr::ddply(data, "gr", summarise, deciles=q1469(obs))`
  `hd05 <- plyr::ddply(data, "gr", summarise, hd=hd(obs,0.5))`

in order to work with a tibble of variables "gr" and "obs".
Once "data" is changed to "obs" the functions seem to work correctly.

**Comment by GRousselet** [comment]
Hi,
thanks for spotting this bug. It's now been fixed.
