### ISSUE TITLE
Analyze and plot quartiles

### ISSUE THREAD

**Issue by GCamp6** [GRousselet/rogme#4]
Is there a simple way to select to analyze and plot just the quartiles instead of the deciles? I tried to have a look at the functions (plot_scat2 for example) but it seemed to me to be hard coded and I do not have the abilities to rewrite the functions..

**Comment by GRousselet** [comment]
Hi,
for the shift function, you can enter the quantiles you want to estimate as an input.
For instance:
shifthd_pbci(df, obs ~ gr, q = c(.25,.5,.75)) # quartiles only
plot_hd_ci(data = out, qseq = c(.25,.5,.75))
For plotting:
plot_scat2d() plots only the quartiles.

If you want flexibility in the quantiles to plot, I can update a function for you. What's your design?

**Comment by GCamp6** [comment]
Thanks, added the q = c(.25,.5,.75) parameter for calculating the shift function with `shifthd_pbci`, if I want to plot it with `plot_sf(sf, plot_theme = 2)` I get error: 
`Error in if (all.equal(df$q, seq(0.1, 0.9, 0.1))) { : 
  argument is not interpretable as logical`

But if I use `plot_scat2` I get the proper plot with all the deciles and the quartiles connected with the colored trend lines.

It's fine to add the q paramenter, I'm still in the testing phase with different configurations
