### ISSUE TITLE
plot_pbsf does not exist

### ISSUE THREAD

**Issue by jimcost** [GRousselet/rogme#6]
The main {rogme} page states:

> In rogme, the shift function can be calculated using:
> 
>     shifthd() or shifthd_pbci() for independent groups
>     shiftdhd() or shiftdhd_pbci() for dependent groups
> 
> Illustrations of the results is handled separately by plot_sf() and plot_pbsf()

I installed the {rogme} package today (5/16/2019) and it does not appear to exist. Did I make a mistake along the way?

**Comment by GRousselet** [comment]
Hi Jamie,
thanks for bringing this to my attention. I forgot to update the README (now fixed). 
plot_sf() now handles all the figures.

**Comment by jimcost** [comment]
You're welcome, although I'm receiving an error trying to plot:

```
> sf <- shifthd_pbci(data = df, formula = T1pre ~ postTreat, nboot = 200, q = c(.25,.5,.75))
> psf <- plot_sf(sf, plot_theme = 2)
Error in if (all.equal(df$q, seq(0.1, 0.9, 0.1))) { : 
  argument is not interpretable as logical
```

**Comment by jimcost** [comment]
It appears I am not alone in the issue: https://github.com/GRousselet/rogme/issues/4#issuecomment-460181697

**Comment by GRousselet** [comment]
ok, i see. I’ll fix the problem tomorrow.


On 21 May 2019, at 19:53, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


It appears I am not alone in the issue: #4 (comment)<https://github.com/GRousselet/rogme/issues/4#issuecomment-460181697>

**Comment by GRousselet** [comment]
Hi Jamie,
can you give a shot to the updated version?
Shouldn’t crash now.
What i don’t understand is why the function worked in the vignettes...

On 17 May 2019, at 20:39, Jamie <notifications@github.com<mailto:notifications@github.com>> wrote:


You're welcome, although I'm receiving an error trying to plot:

> sf <- shifthd_pbci(data = df, formula = T1pre ~ postTreat, nboot = 200, q = c(.25,.5,.75))
> psf <- plot_sf(sf, plot_theme = 2)
Error in if (all.equal(df$q, seq(0.1, 0.9, 0.1))) { :
  argument is not interpretable as logical
