### ISSUE TITLE
plot_sf() error with shifthd_pbci() output

### ISSUE THREAD

**Issue by hsteptoe** [GRousselet/rogme#7]
Related to #4 and #6, the `plot_sf()` error still seems to exist when used with `shifthd_pbci()`.  I'm not exactly clear what the outcome of #4 and #6 where, so starting a new issue for clarity.

The error can be reproduced with:
```R
library(rogme)
library(ggplot2)

#> generate data
set.seed(21)
g1 <- rnorm(1000) + 6
g2 <- rnorm(1000) * 1.5 + 6

#> make tibble
df <- mkt2(g1, g2)

#> compute shift function
# sf <- shifthd(data = df, formula = obs ~ gr, nboot = 200)
sf <- shifthd_pbci(data = df, formula = obs ~ gr, nboot = 200, q = c(.1,.25,.5,.75,.9))

#> plot shift function
psf <- plot_sf(sf, plot_theme = 1)
```
and returns an error:
```
Error in if (all.equal(df$q, seq(0.1, 0.9, 0.1))) { : 
  argument is not interpretable as logical
```

Coincidentally, using `sf` in `plot_hd_links()` works fine.

**Comment by GRousselet** [comment]
Hi,
I've added isTRUE to that logical statement, which seems to fix the problem.
Let me know if it works for you.
Thanks for reporting the bug.

**Comment by hsteptoe** [comment]
Yep, this works for me.  Thanks for the fix!
