### ISSUE TITLE
`plot_hsf_pb_dist` missing `qseq`

### ISSUE THREAD

**Issue by hsteptoe** [GRousselet/rogme#8]
The `plot_hsf_pb_dist()` function seems to be missing a definition of `qseq` at [L225](https://github.com/GRousselet/rogme/blob/974b5789b9c81f884636b6c6ee050d3ca8f9820a/R/hsf_plot.R#L225).

Changing this line to `scale_y_continuous(breaks = data$quantiles)` fixes the problem for me.

**Comment by GRousselet** [comment]
Thanks for spotting the problem! I'll merge your solution now.
